### ISSUE TITLE
[EPIC] Optimize the CI pipeline

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#1142]
### Describe the proposal

We just open source our project. Now we should optimize the CI pipeline to accelerate the speed of dev.

### Task list

 - [ ] Split the IT to more pipelines
 - [ ] Spit the UT to more pipelines
 - [ ] Use the pipeline of the developer
 - [ ] Cache maven packages
 - [ ] Remove the limit of concurrency
 - [x] https://github.com/datastrato/gravitino/issues/1079

**Comment by yuqi1129** [comment]
@qqqttt123
Maybe #998 is also a part of this.

**Comment by mchades** [comment]
I'm going to close this issue since it's outdated and duplicated with #3834
