### ISSUE TITLE
[EPIC] The support of the user system

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#1182]
### Describe the proposal

For Gravitino, we will support to manage the privilleges. The basic of privileges is the user system. 

### Task list

- [ ] Polish the document of design doc
- [ ] Use the real user to record the audit information
        https://github.com/datastrato/gravitino/issues/1206
- [ ] Use the real user to execute operations
        https://github.com/datastrato/gravitino/issues/596
- [ ] Propose a proper interface of user system
- [ ] The support of Ranger
- [ ] The support of IAM
- [ ] The support of Gravitino internal privileges system
- [ ] The support of JDBC
- [ ] The support of Hive
- [ ] The storage of user information
- [ ] The api of user management

**Comment by qqqttt123** [comment]
This issue if out of date, I will create an new issue to track other things.
