### ISSUE TITLE
[EPIC] Support partition management

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#1575]
### Describe the proposal

We have already added support for creating partitioned tables, but we lack the ability to manage partitions. We may need to use partition management functionality in the following scenarios:

- To define a table with a special partitioning strategy, such as range and list, it is necessary to create partitions at the table definition stage

- For tables where partitions cannot be generated automatically, partition management is necessary to create partitions in advance before writing data.

- Obtaining partition statistics can be used for data governance, partition pruning, and other purposes.

### Task list

- [x] #1576 
- [x] #1655 
- [x] #1675 
- [x] #1678 
- [x] #1673 
- [x] #1719 
- [x] #1768 
- [x] #1769 
- [x] #1774 
- [x] #1776 
- [x] #3140
- [x] #2266 
- [x] #3064 
- [x] #3368 
- [ ] Iceberg catalog supports partition management
- [ ] Mysql catalog supports partition management
- [ ] PostgreSQL catalog supports partition management
