### ISSUE TITLE
[EPIC] Design and implement the basic metadata spec

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#3]
Metadata schema system is the core system in Unified Catalog to describe the entities, including memory structure, on-wire format and storage layout. 

This umbrella issue tracks the whole design and implementation of Unified Catalog' schema system, including:

1. Metadata entity design & implement.
2. Entity serialization and deserialization protocol design & implement.
3. Entity storage layout design & implement.

Subtasks are listed here:

- [x] Metadata and Type Spec design ( lakehouse, zone, table, column and other basic entities), including memory structure, on-wire and storage layout design. #11 
- [x] Metadata and Type Spec implementation (memory structure). #12 
- [x] Metadata on-wire protocol implement. #16 
- [x] Medata storage layout implement. #21
