### ISSUE TITLE
[EPIC] Get people to sign contributors/maintainers table

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3359]
### Describe the proposal

Any significant contributions need to add their name to the contributor table to make it easier to do IP clearance and transfer our code base to the ASF.

### Task list

- [x] Ask missing people to add themselves to the maintainers table
- [x] Email contributors we have an email addresses for
- [x] Create GitHub issue for all others
- [x] Follow up if there's no response
