### ISSUE TITLE
[EPIC] Type System enhancement

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#3427]
### Describe the proposal

We have developed a universal type system with a basic implementation in Gravitino. 

However, with the growth of users and the richness of application scenarios, we have encountered some issues that cannot be resolved by the current implementation, so we need to enhance the type system to cover more usage scenarios.

### Task list

 - [x] investing and design enhance solution:  #2373 
 - [x] #3589 
 - [x] support `ExternalType` #3500 
 - [x] #2340 
 - [x] Add parameters to `IntervalType` #2596 
 - [x] support MySQL `datetime` type #1761
