### ISSUE TITLE
[EPIC] Hive catalog support external table

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#3816]
### Describe the proposal

Hive external table is the basic table type of Hive, and we need to support basic operations on Hive external tables in the Hive catalog.

### Task list

 - [ ] Hive catalog support creates external table
 - [ ] Hive catalog support alters external table
 - [ ] Hive catalog support list/drop external table
 - [ ] Trino connector support external table
 - [ ] Spark connector support external table
 - [ ] Flink connector support external table

**Comment by featherchen** [comment]
Hi @mchades ,  I am wondering if there is any progress on this issue, if not, I want to start working on it.

**Comment by mchades** [comment]
> Hi @mchades , I am wondering if there is any progress on this issue, if not, I would like to start working on it.

Not started yet, it's up to you to start.

**Comment by mchades** [comment]
My mistake, Hive catalog already supported the external table:

https://github.com/apache/gravitino/blob/9edc67ba3dddf6c5075611db354c80960ee7eb26/catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveTable.java#L62-L64
