### ISSUE TITLE
[EPIC] Transfer the project the ASF

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3830]
### Describe the proposal

Transfer Gravitino the Apache Software Foundation

### Task list

 - [x]  Add Gravitino to podlings.xml
 - [x]  Raise ASF Jira to set up LDAP / domains
 - [x]  Create mailing lists
 - [x]  Sign and submit software grant
 - [x]  Add mentors in Whimsey
 - [x]  Have all PPMC members sign ICLAs
 - [x] Have missing contributors sign ICLAs
 - [x]  Add all PPMC members in Whimsey
 - [x]  Have all PPMC members sign up for mailing lists
 - [x] Have all PPMC members setup ASF accounts (including GitHub access)
 - [x] Transfer GitHub Repos (need ICLAs and SGA complete)
 - [x] Submit name search

**Comment by justinmclean** [comment]
PPMC members who need to sign ICLAs include:
Charlie Cheng (@charliecheng630)
Kang Zhou (@zhoukangcn)
Minghuang Li (@mchades)
Qi Yu (@yuqi1129)
Xin Yong (@YxAc)
Xiaojin Fang (@FANNG1)
Xiao Xu (@theoryxu)
Yunqing Wei (@Clearvive)
Ziva Li (@zivali)

To fill them out you need to read this:
https://www.apache.org/licenses/contributor-agreements.html#clas

And then complete this form:
https://www.apache.org/licenses/icla.pdf

Note that:
- the address should be your personal one and not your company address
- you need to sign the form and not use a script font

**Comment by justinmclean** [comment]
Missing contributors who need to sign ICLAs include:
@ajayl83
@NIRMALraki
@Yangxuhao123
@ zhaoyongjie

The same form needs to be used but you do not need to request an Apache id.

**Comment by justinmclean** [comment]
@zhaoyongjie I'll send you an email to sort out

**Comment by YxAc** [comment]
@justinmclean thanks for the mention, my name is _Xing Yong (@YxAc)_ not _Xin Yong (@YxAc)_ , thx.

**Comment by justinmclean** [comment]
Thanks @YxAc I've corrected that, but what is important is that your ICLA form is filled out.

**Comment by YxAc** [comment]
> Thanks @YxAc I've corrected that, but what is important is that your ICLA form is filled out and submitted to the ASF secretary.

Get.

**Comment by NIRMALraki** [comment]
Hi, team I would like my name to be mentioned among the contributors list , thank you!.

**Comment by justinmclean** [comment]
@zhaoyongjie I emailed you but got no response. Your contributions are tied to your GitHub id and we can't change that.

**Comment by justinmclean** [comment]
@NIRMALraki Anyone who has contributed to the project is automatically listed as a contributor, there is no need to ask. As you have made several contributions, we would like you to sign an ICLA as that would help transfer the software to the ASF. Can you do that?

**Comment by zhaoyongjie** [comment]
@justinmclean I've replied you from private mail. I just realized we were transferring the code base to Apache need approval from every contributors. I've signed the ICLA, and now will sent it you as soon as possible. Thanks for your work and patience.

**Comment by justinmclean** [comment]
Charlie Cheng @charliecheng630 and Xiao Xu @theoryxu looks like we are missing ICLAs from you. Is this the case? If so do you know when you could submit one?

**Comment by charliecheng630** [comment]
@justinmclean I have just completed signing the ICLA and have sent it out. Thanks!

**Comment by justinmclean** [comment]
Thanks @charliecheng630 for that

**Comment by theoryxu** [comment]
> Charlie Cheng @charliecheng630 and Xiao Xu @theoryxu looks like we are missing ICLAs from you. Is this the case? If so do you know when you could submit one?

Sorry, I'm late. I was on vacation last week.
I have signed the ICLA and sent it just now, Thank you.

**Comment by justinmclean** [comment]
Thanks @theoryxu for submitting that

**Comment by justinmclean** [comment]
All initial committer ICLAs have been submitted and Apache accounts created. The software grant has also been submitted.

**Comment by justinmclean** [comment]
For name search see https://issues.apache.org/jira/browse/PODLINGNAMESEARCH-223

**Comment by justinmclean** [comment]
We're currently waiting on ASF Infra to have the repositories transferred, but hopefully, that should happen in the next couple of days.

**Comment by jerryshao** [comment]
I think we can close this issue now? @justinmclean

**Comment by justinmclean** [comment]
No not yet. We also need several PPMC members (8 or 9 off top of my head) to complete setup their ASF accounts.

**Comment by mchades** [comment]
> No not yet. We also need several PPMC members (8 or 9 off top of my head) to complete setup their ASF accounts.

Could you please list the names here so that we can help to inform them

**Comment by justinmclean** [comment]
I've sent them an email - also sent to the Gravitino private email list.

**Comment by justinmclean** [comment]
as complete as it will be
