### ISSUE TITLE
[EPIC] Works to do after entering ASF Incubating

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4034]
### Describe the proposal

There are many works we need to do after entering the ASF incubator, so here listed several things we should do recently:

### Task list

- [ ] #4032 
- [ ] #4031 
- [ ] Update the license header to use Apache V2 license header instead of Company's one
- [ ] Update the package name to use `org.apache.gravitino`
- [ ] Update the README to claim an Apache incubating project
- [ ] Update all the documents to refer to Apache Gravitino, not Gravitino or Datastrato Gravitino
- [ ] Transfer the slack to Apache Gravitino Slack
- [ ] Bootstrap the Apach Gravitino website

**Comment by jerqi** [comment]
We should modify the license and document of playground, too.

**Comment by jerryshao** [comment]
> We should modify the license and document of playground, too.

Yes, please also create issues to track this.
