### ISSUE TITLE
[EPIC] Make Gravitino run with cloud storage

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4396]
### Describe the proposal

This EPIC issue aims to make Gravitino support running with cloud storage, like S3, ADLS, GCS, etc.

The background is that current Gravitino only tests against HDFS, but with the more demands of cloud object storage, we should make sure that Gravitino can work well with cloud storage.

The work here includes necessary code changes, configuration supports, validations and tests.

### Task list

- [ ] Hive catalog supports cloud storage.
- [ ] Iceberg catalog supports cloud storage
- [ ] Fileset supports cloud storage
- [ ] Iceberg rest catalog server supports cloud storage
- [ ] Paimon supports cloud storage
- [ ] Spark supports running on cloud storage
- [ ] Flink supports running on cloud storage
- [ ] Trino supports running on cloud storage
