### ISSUE TITLE
[EPIC] Prepare for 0.6.0 release

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4480]
### Describe the proposal

This epic issue tracks the work of releasing Gravitino 0.6.0 (The first incubating release). 

### Task list

- [x] License check for branch-0.6 @justinmclean .
- [x] Release script / document ready #4417 
- [x] Make sure maven repo, Pypi repo, Dockerhub is ready @yuqi1129 
- [x] Tag release and call for vote @jerryshao 
- [x] Things after release.
    - [x] docker image release @jerqi 
    - [x] playground update for 0.6.0 @jerqi 
    - [x] doc publish @LauraXia123 
    - [x] release note and annoucement. @jerryshao

**Comment by jerqi** [comment]
Docker image release may need some privileges which I don't have.
