### ISSUE TITLE
[EPIC] Graviton 0.2.0 release

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#477]
### Describe the proposal

This epic issue tracks the works of releasing the Graviton 0.2.0 version. The target release date is 25 Oct.

Here is the checklist for 0.2.0 release.

- [x] **Test**: including unit test and integration test to cover all the features in 0.2.0.
- [x] **Documentation**, #479 
- [x] #513
- [x] **Verification**: release package verification.
- [x] **Publish**:
  - [x] Publish libs to maven repo.
  - [x] Publish bin/src package to Github.

CC @justinmclean please check if you need anything to add. I think the heavy work is to have a relatively complete doc, I will create a separate issue and involve all to finish the doc works.
