### ISSUE TITLE
[EPIC] Add docs for Graviton

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#479]
### Describe the proposal

This issue tracks the work of adding documents for Graviton, this includes:

- [x] Add readme file to Graviton. @jerryshao #105 
- [x] Add a document framework (like Jekyll, etc.) to Graviton. @xunliu #492 
- [x] #533
- [x] #551
- [x] Developer's guide about how to build, test. (must have) @xunliu 
- [x] Configuration docs, including the explanation of all the configurations for Graviton. (must have) @yuqi1129  #494 
- [x] Catalog docs, including Hive and Lakehouse-iceberg catalog docs on how to use, and configure. (must have) @sandflee  @mchades #562  #516 #537 
- [x] Trino docs, including how to use Trino with Graviton. (must have) @diqiu50 #525 
- [x] #564
