### ISSUE TITLE
[EPIC] Add ui support for creating, editing, viewing and deleting schema

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5140]
### Describe the proposal

Add support for create/edit/delete schema

### Task list

- [x] https://github.com/apache/gravitino/issues/5141
- [x] https://github.com/apache/gravitino/issues/5142
- [x] https://github.com/apache/gravitino/issues/5143
