### ISSUE TITLE
[EPIC] Add ui support for creating, editing, viewing, and deleting fileset

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5167]
### Describe the proposal

Add support for creating, editing, and deleting fileset

### Task 

- [x] https://github.com/apache/gravitino/issues/5168
- [x] https://github.com/apache/gravitino/issues/5169
- [x] https://github.com/apache/gravitino/issues/5170
