### ISSUE TITLE
[EPIC] Open source Graviton

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#517]
### Describe the proposal

Make the graviton repo public and available under an open source license and governance model.

### Task list

- [x] #518
- [ ] Make repo public
- [ ] Add repo info to the website
- [ ] Set license in GitHub (if needed)
- [x] Add and tag first release
- [ ] Add installation instructions
- [ ] Add security information
- [ ] Add information on the governance model
- [ ] Create new contributor documentation
- [ ] Add information on signing and submitting ICLAs
- [ ] Add code of conduct
- [ ] Create getting started example
