### ISSUE TITLE
[EPIC] Support python client for table operations

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#5198]
### Describe the proposal

Support relational catalog operations for Python client.

### Task list

Support relational catalog operations for Python client
- [ ] Support Column data type
  - [docs](https://gravitino.apache.org/docs/0.6.1-incubating/manage-relational-metadata-using-gravitino#apache-gravitino-table-column-type)
 - related java issue: [#599](https://github.com/apache/gravitino/issues/599) #3427
- [ ] Support  Expression system
  - [docs](https://gravitino.apache.org/docs/0.6.1-incubating/expression)
  - related java issue: #600
- [ ] Support  Table partitioning, bucketing and sort ordering and indexes
  - [docs](https://gravitino.apache.org/docs/0.6.1-incubating/table-partitioning-bucketing-sort-order-indexes)
  - related java issues: #248 #264
- [ ] Support  Column default value
 - [docs](https://gravitino.apache.org/docs/0.6.1-incubating/manage-relational-metadata-using-gravitino#table-column-default-value)
   - related java issues: #896
- [ ] Support  Table partition management
  - [docs](https://gravitino.apache.org/docs/0.6.1-incubating/manage-table-partition-using-gravitino)
  - related issues: #1575

**Comment by tsungchih** [comment]
@unknowntpo Just a heads-up. I started working on support for alter table
