### ISSUE TITLE
[Subtask] Support Table partitioning, bucketing and sort ordering and indexes

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#5199]
### Describe the subtask

docs: https://gravitino.apache.org/docs/0.6.1-incubating/table-partitioning-bucketing-sort-order-indexes/
related issues: #248  #264 

### Parent issue

#5198

**Comment by tsungchih** [comment]
I was wondering if I could take this one. Here's the scope and the plan for this issue. And hope my understanding is correct.

The 1st PR

- [x] PartitionDTO.java
- [x] IdentityPartitionDTO.java
- [x] ListPartitionDTO.java
- [x] RangePartitionDTO.java

PRs:
- #7902 
- #7904 

The 2nd PR

- [x] JsonUtils.java (PartitionDTOSerializer, PartitionDTODeserializer)

PRs:
- #8128 

The 3rd PR

- [x] Partitioning.java
- [x] IdentityPartitioningDTO.java
- [x] YearPartitioningDTO.java
- [x] MonthPartitioningDTO.java
- [x] DayPartitioningDTO.java
- [x] HourPartitioningDTO.java
- [x] BucketPartitioningDTO.java
- [x] ListPartitioningDTO.java
- [x] RangePartitioningDTO.java
- [x] TruncatePartitioningDTO.java
- [x] FunctionPartitioningDTO.java
 
PRs: 
- #8004 
- #8129 

The 4th PR

- [x] JsonUtils.java (PartitioningSerializer, PartitioningDeserializer)

PRs:
- #8363 

The 5th PR

- [x] DistributionDTO.java
- [x] JsonUtils.java (DistributionSerializer, DistributionDeserializer)

PRs:
- #8185 
- #8458 

The 6th PR
- [x] SortOrderDTO.java
- [x] JsonUtils.java (SortOrderSerializer, SortOrderDeserializer)

PRs:
- #8220 
- #8459 

The 7th PR
- [x] Index.java
- [x] Indexes.java

PRs:
- #8143 

The 8th PR
- [x] IndexDTO.java
- [x] JsonUtils.java (IndexSerializer, IndexDeserializer)

PRs:
- #8262 
- #8457

**Comment by unknowntpo** [comment]
@tsungchih Okay.

**Comment by jerryshao** [comment]
Hi @tsungchih @unknowntpo, how many PRs do we still need for this issue?

**Comment by unknowntpo** [comment]
> I was wondering if I could take this one. Here's the scope and the plan for this issue. And hope my understanding is correct.
> 
> The 1st PR
> 
> * [x]  PartitionDTO.java[x]  IdentityPartitionDTO.java[x]  ListPartitionDTO.java[x]  RangePartitionDTO.java
> 
> The 2nd PR
> 
> * [x]  JsonUtils.java (PartitionDTOSerializer, PartitionDTODeserializer)
> 
> The 3rd PR
> 
> * [x]  Partitioning.java[x]  IdentityPartitioningDTO.java[x]  YearPartitioningDTO.java[x]  MonthPartitioningDTO.java[x]  DayPartitioningDTO.java[x]  HourPartitioningDTO.java[x]  BucketPartitioningDTO.java[x]  ListPartitioningDTO.java[x]  RangePartitioningDTO.java[x]  TruncatePartitioningDTO.java[x]  FunctionPartitioningDTO.java
> 
> The 4th PR
> 
> * [ ]  JsonUtils.java (PartitioningSerializer, PartitioningDeserializer)
> 
> The 5th PR
> 
> * [x]  DistributionDTO.java[ ]  JsonUtils.java (DistributionSerializer, DistributionDeserializer)
> 
> The 6th PR
> 
> * [x]  SortOrderDTO.java[ ]  JsonUtils.java (SortOrderSerializer, SortOrderDeserializer)
> 
> The 7th PR
> 
> * [x]  Index.java[x]  Indexes.java
> 
> The 8th PR
> 
> * [x]  IndexDTO.java[ ]  JsonUtils.java (IndexSerializer, IndexDeserializer)

Seems like it's documented at here, @tsungchih could you mention related PR for each task in the task list ?

**Comment by tsungchih** [comment]
> > I was wondering if I could take this one. Here's the scope and the plan for this issue. And hope my understanding is correct.
> > The 1st PR
> > 
> > 
> > * [x]   PartitionDTO.java[x]  IdentityPartitionDTO.java[x]  ListPartitionDTO.java[x]  RangePartitionDTO.java
> > The 2nd PR
> > 
> > 
> > * [x]   JsonUtils.java (PartitionDTOSerializer, PartitionDTODeserializer)
> > The 3rd PR
> > 
> > 
> > * [x]   Partitioning.java[x]  IdentityPartitioningDTO.java[x]  YearPartitioningDTO.java[x]  MonthPartitioningDTO.java[x]  DayPartitioningDTO.java[x]  HourPartitioningDTO.java[x]  BucketPartitioningDTO.java[x]  ListPartitioningDTO.java[x]  RangePartitioningDTO.java[x]  TruncatePartitioningDTO.java[x]  FunctionPartitioningDTO.java
> > The 4th PR
> > 
> > 
> > * [ ]   JsonUtils.java (PartitioningSerializer, PartitioningDeserializer)
> > The 5th PR
> > 
> > 
> > * [x]   DistributionDTO.java[ ]  JsonUtils.java (DistributionSerializer, DistributionDeserializer)
> > The 6th PR
> > 
> > 
> > * [x]   SortOrderDTO.java[ ]  JsonUtils.java (SortOrderSerializer, SortOrderDeserializer)
> > The 7th PR
> > 
> > 
> > * [x]   Index.java[x]  Indexes.java
> > The 8th PR
> > 
> > 
> > * [x]   IndexDTO.java[ ]  JsonUtils.java (IndexSerializer, IndexDeserializer)
> 
> Seems like it's documented at here, [@tsungchih](https://github.com/tsungchih) could you mention related PR for each task in the task list ?

Done!

**Comment by tsungchih** [comment]
> Hi [@tsungchih](https://github.com/tsungchih) [@unknowntpo](https://github.com/unknowntpo), how many PRs do we still need for this issue?

@jerryshao Three PRs (serdes for DistributionDTO, SortOrderDTO, and IndexDTO) left for this issue.

**Comment by jerryshao** [comment]
> > Hi [@tsungchih](https://github.com/tsungchih) [@unknowntpo](https://github.com/unknowntpo), how many PRs do we still need for this issue?
> 
> [@jerryshao](https://github.com/jerryshao) Three PRs (serdes for DistributionDTO, SortOrderDTO, and IndexDTO) left for this issue.

Got it, thanks.

**Comment by tsungchih** [comment]
@jerryshao @unknowntpo I think we are ready to close this issue.
