### ISSUE TITLE
[Subtask] Support Column and its default value

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#5202]
### Describe the subtask

@xunliu @SophieTech88 This issue should also implement `public class Column` at `api/src/main/java/org/apache/gravitino/rel/Column.java`

- [docs](https://gravitino.apache.org/docs/0.6.1-incubating/manage-relational-metadata-using-gravitino#table-column-default-value)
- related java issues: https://github.com/apache/gravitino/issues/896

### Parent issue

#5198 

### Related PRs:

- [x] https://github.com/apache/gravitino/pull/6542
- [x]  https://github.com/apache/gravitino/pull/6903
- [x] https://github.com/apache/gravitino/pull/7241
- [x] #7497 
- [x] #7498 
- [x] #7357 
- [x] #7497 

c.c. @tsungchih

**Comment by tsungchih** [comment]
I was wondering if I could take this one provided that there's no one working on it.

**Comment by justinmclean** [comment]
Sure, just be aware this is a slightly old issue and it may have already been done.

**Comment by tsungchih** [comment]
Thanks for the prompt reply and the reminder. So far in the repo, I have not seen the code related to this issue though. After having dedicated myself into the code for a couple of hours, I came out the following list of Java classes needs to be implemented in client-python. 

- [x] Column
- [x] ColumnDTO
- [x] SupportsTags
- [x] Tag
- [x] PartitionUtils
- [x] FieldReferenceDTO
- [x] FuncExpressionDTO
- [x] LiteralDTO
- [x] UnparsedExpressionDTO
- [x] FunctionArg
- [x] TypeSerializer
- [x] TypeDeserializer
- [x] ColumnDefaultValueSerializer
- [x] ColumnDefaultValueDeserializer
- [x] NoSuchTagException
- [x] TagAlreadyExistsException

Could you please take a look at it to see if I missed something?
I feel the PR for this issue will be a little bit fat. Would you prefer to embrace them all in a single PR or multiple PRs?

Here's the initial version of class diagram for your reference.

```mermaid
---
title: Class Diagram
---
classDiagram
    class Tag {
        <<interface>>
        +PROPERTY_COLOR = "color"
        +name(self) str
        +comment(self) str
        +properties(self) Dict[str, str]
        +inherited(self) Optional[bool]
    }
    class SupportsTags {
        <<interface>>
        +list_tags(self) List[str]
        +list_tags_info(self) List[Tag]
        +get_tag(self, name: str) Tag
        +associate_tags(self, tags_to_add: List[str], tags_to_remove: List[str]) List[str]
    }
    class Column {
        <<interface>>
        +name(self) str
        +data_type(self) Type
        +comment(self) Optional[str]
        +nullable(self) bool
        +auto_increment(self) bool
        +default_value(self) Expression
        +supports_tags(self) SupportsTags
        +of(name: str, data_type: Type, comment: Optional[str]=None, nullable: bool=True, auto_increment: bool=False, default_value: Optional[Expression]=None) ColumnImpl
    }
    class ColumnImpl {
        __init__(self, name: str, data_type: Type, comment: Optional[str], nullable: bool, auto_increment: boool, default_value: Optional[Expression])
    }
    class ColumnDTO {
        -name: str
        -data_type: Type
        -comment: Optional[str]
        -nullable: bool
        -auto_increment: bool
        -default_value: Expression
    }
    class ColumnDefaultValueSerde {
        +serialize(cls, data: Expression) Optional[dict]
        +deserialize(cls, data: Optional[dict]) Expression
    }
    class FieldReferenceDTO {
        -field_name: List[str]
        __init__(self, field_name: List[str])
        -field_name(self) List[str]
        -arg_type(self) FunctionArg.ArgType
    }
    class FuncExpressionDTO {
        -function_name: str
        -function_args: List[FunctionArg]
        __init__(self, function_name: str, function_args: List[FunctionArg])
        +args(self) List[FunctionArg]
        +function_name(self) str
        +arguments(self) List[Expression]
        +arg_type(self) FunctionArg.ArgType
    }
    class PartitionUtils {
        +validate_field_existence(columns: List[ColumnDTO], field_name: List[str]) None
    }
    class FunctionArg {
        <<interface>>
        EMPTY_ARGS: list[FunctionArg] = []
        +arg_type() ArgType
        +validate(columns: list[ColumnDTO]) None
    }
    class LiteralDTO~str~ {
        +NULL: LiteralDTO = LiteralDTO("NULL", Types.NullType.get())
        -value: str
        -data_type: Type
        __init__(self, value: str, data_type: Type) None
        +value() str
        +data_type() Type
        +arg_type() FunctionArg.ArgType
        __repr__(self) str
    }
    class SerdeBase~T,U~ {
        <<interface>>
        +serialize(cls, data: T) U
        +deserialize(cls, data: U) T
    }
    class TypesSerde {
        +serialize(cls, data: Type) str
        +deserialize(cls, data: str) Type
    }
    
    Auditable <|-- Tag
    Expression <|-- Literal

    Tag <.. SupportsTags
    SupportsTags <.. Column
    Column <|.. ColumnImpl: implements
    Column <|.. ColumnDTO: implements
    ColumnDTO <.. FunctionArg
    ColumnDTO <.. PartitionUtils
    DataClassJsonMixin <|.. ColumnDTO: implements
    SerdeBase <|.. TypesSerde: implements
    SerdeBase <|.. ColumnDefaultValueSerde: implements
    Expression <|-- FunctionArg
    PartitionUtils <.. FunctionArg
    TypesSerde <.. ColumnDTO
    ColumnDefaultValueSerde <.. ColumnDTO

    Literal <|.. LiteralDTO: implements
    FunctionArg <|.. LiteralDTO: implements
    NamedReference <|.. FieldReferenceDTO: implements
    FunctionArg <|.. FieldReferenceDTO: implements
    FunctionArg <|.. UnparsedExpressionDTO: implements
    UnparsedExpression <|.. UnparsedExpressionDTO: implements
    FunctionExpression <|.. FuncExpressionDTO: implements
    FunctionArg <|.. FuncExpressionDTO: implements
    LiteralDTO <.. ColumnDefaultValueSerde
    FieldReferenceDTO <.. ColumnDefaultValueSerde
    FuncExpressionDTO <.. ColumnDefaultValueSerde
    UnparsedExpressionDTO <.. ColumnDefaultValueSerde
```

**Comment by justinmclean** [comment]
Smaller PRs are easier to review so if you can break it up into several PRs that would be a great help.

**Comment by tsungchih** [comment]
The plan is to have four PRs. Classes implemented in each PR are listed as follows for your reference.

- PART1: Column, SupportsTags, Tag, NoSuchTagException, TagAlreadyExistsException
- PART2: FunctionArg, PartitionUtils, ColumnDTO, TypesSerializer, TypesDeserializer
- PART3: LiteralDTO, FieldReferenceDTO, FuncExpressionDTO, UnparsedExpressionDTO
- PART4: ColumnDefaultValueSerializer, ColumnDefaultValueDeserializer

**Comment by justinmclean** [comment]
Thanks, that sounds fine to me.

**Comment by tsungchih** [comment]
@jerryshao I was wondering if we should keep this story opened since some further implementations need to be done, such as classes of FieldReferenceDTO, FuncExpressionDTO, UnparsedExpressionDTO and the Serdes of column default value.

**Comment by unknowntpo** [comment]
@tsungchih Still have some works to do on this issue, so reopened.

**Comment by tsungchih** [comment]
@jerryshao @unknowntpo I found bugs in instance comparison (dunder method `__eq__`) of [`ListType`](https://github.com/apache/gravitino/blob/main/clients/client-python/gravitino/api/types/types.py#L817-L823), [`UnionType`](https://github.com/apache/gravitino/blob/main/clients/client-python/gravitino/api/types/types.py#L965-L977), and [`UnparsedType`](https://github.com/apache/gravitino/blob/main/clients/client-python/gravitino/api/types/types.py#L1018-L1030) when developing unit tests of column default value serdes for `ColumnDTO`. The intention of the current implementation for each one of them is contrary.

Here's an example from `UnparsedType`.

```python
       def __eq__(self, other):
            """
            Compares two unparsed_type objects for equality.

            Args:
                other: The other unparsed_type object to compare with.

            Returns:
                True if both unparsed_type objects have the same unparsed type string, False otherwise.
            """
            if not isinstance(other, Types.UnparsedType):
                return self._unparsed_type == other.unparsed_type()
            return False
```

The above implementation returns `False` if the data type of `other` is the same as the instance itself without comparing anything.

Here are two strategies for us to move forward:

1. Fix them within my next PR together with the column default value serdes.
2. Raise yet another issue independently for the bug fixes and then get back to the PR of column default value serdes.

Which one would you prefer?

**Comment by unknowntpo** [comment]
> the

Okay, approach 1 is Okay for me.

**Comment by jerryshao** [comment]
Is there any follow-up works for this issue, can we close it? @tsungchih @unknowntpo

**Comment by unknowntpo** [comment]
> Is there any follow-up works for this issue, can we close it? [@tsungchih](https://github.com/tsungchih) [@unknowntpo](https://github.com/unknowntpo)

@jerryshao  This can be closed, and I noticed that we are lacked of integration tests about table operations,
so I've added a subtask about this at #7750 . We can do this after other tasks are done in epic https://github.com/apache/gravitino/issues/5198
