### ISSUE TITLE
[EPIC] Implement GVFS fuse tools to access Gravitino file sets in the POSIX Protocols

### ISSUE THREAD

**Issue by diqiu50** [apache/gravitino#5504]
### Describe the proposal

 Implement GVFS fuse tools to access Gravitino file sets in the POSIX  Protocols

```
# init fileset
fs_context = gvfs.fs.context(server_uri="http://localhost:8090", metalake_name="test_metalake", properties=config_gv)
fileset = fs_context.createFileset(path="fileset/test_catalog/schema1/ai_fileset", properties=config_fs)

# mount dir
root_dir = fileset.getRoot()
mount_dir = "/mnt/myfileset"
gvfs.util.mount(root_dir, mount_dir, properties=fileset.config())

# read file in the mounted directory
file_f = read(mountdir + "/0567/a.txt")
print(file_f.readToString())

# unmount
gvfs.util.unmount(mount_dir)
```

```
#mount
gvfsutil mount --gvfs_path gvfs://fileset/test_catalog/schema1/ai_fileset --mount_path /mnt/ai_fileset --config /tmp/gvfs.config 

#unmount
gvfsutil unmount /mnt/fileset/test_catalog/schema1/ai_fileset
```

### Task list

- [ ] Gvfs - Fuse Project Setup
- [ ] Code Layout
- [ ] Fuse API Handling
- [ ] Gvfs basics filesystem APIs
- [ ] Gvfs Metadata Cache
- [ ] Gvfs Data Cache
- [ ] Gravitino Fileset client go implementation
- [ ] Gvfs Support for JuiceFS
- [ ] Gvfs Support for S3
- [ ] Support for Mounting to Catalog and Schema Levels
- [ ] Gvfs Fuse Tools
- [ ] Gvfs Fuse Python Support
- [ ] Gvfs Permissions and Quotas
- [ ] Gvfs Monitoring and Metrics
- [ ] Gvfs Read/Write Performance Optimization

**Comment by alan910127** [comment]
Hi, I have a few questions regarding the design. Could it be adjusted?
1. Python typically follows the `snake_case` convention for variable and function names.
2. Most CLI tools use the `--some-option` format with hyphens instead of `--some_option` with underscores. The widely used command line argument parser crate, [clap](https://github.com/clap-rs/clap), also follows the hyphenated format by default.
