### ISSUE TITLE
[EPIC] Add e2e test case for creating schema/topic/table/fileset

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5795]
### Describe the proposal

The current test case is created through the create method of the Java class, and we need to implement the created test case by simulating a click on the UI dialog box

### Task list

- [x] https://github.com/apache/gravitino/issues/5796
- [x] https://github.com/apache/gravitino/issues/5797
- [x] https://github.com/apache/gravitino/issues/5798
- [x] https://github.com/apache/gravitino/issues/5799
