### ISSUE TITLE
[EPIC] Security best practice

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#661]
### Describe the proposal

Follow security best practices and work towards making our software more secure.
- [ ] Set up Dependabot (if possible)
- [x] Set up security policy and reporting process
- [x] Look into using Dependency Track https://dependencytrack.org
- [ ] #707
- [x] #662
